export const skillIcons: Record<string, string> = {
  Python: "python",
  "C/C++": "cplusplus",
  SQL: "/icons/sql.svg",
  Matlab: "/icons/matlab.svg",
  PyTorch: "pytorch",
  TensorFlow: "tensorflow",
  Keras: "keras",
  "Scikit-learn": "scikitlearn",
  NumPy: "numpy",
  Pandas: "pandas",
  Matplotlib: "/icons/matplotlib.svg",
  Seaborn: "/icons/seaborn.png",
  OpenCV: "opencv",
  "PyTorch Geometric (PyG)": "pytorch",
  DGL: "/icons/dgl.png",
  NetworkX: "/icons/networkx.svg",
  Git: "git",
  Docker: "docker",
  Linux: "linux",
  Jupyter: "jupyter",
  "VS Code": "/icons/vscode.svg",
  LaTeX: "latex",
  "AWS (SageMaker, EC2)": "/icons/aws.svg",
  MLflow: "mlflow",
  "Weights & Biases": "weightsandbiases",
};
